# Site settings
course_name: Quantitative Biology - Systems Pharmacology
course_description: "This 6-lecture mini-course is designed to introduce students to Systems Pharmacology, especially as it pertains to cancer, and provide examples of computational tools (primarily Python-based) that aid in interpretation of quantitative drug-response data."
course_semester: "Spring 2023"

baseurl: "/QuantBio" # the subpath of your site, e.g. /blog/
url: "https://vu-csp.github.io/" # the base hostname & protocol for your site

schoolname: "Vanderbilt University -- Cancer Systems Pharmacology & Biology"
schoolurl: "https://vu-csp.github.io"
twitter_username: darrentyson_vu

address: |
    Department of Pharmacology
    Vanderbilt University School of Medicine
    Nashville, TN

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
